// FILE: src/contexts/AuthContext.tsx
//
// CHANGELOG:
// v1.0: Basic auth context
// v1.1: Added createDefaultProfile fallback for new users (Jan 25 fix)
// v1.2: Removed created_at from insert (column doesn't exist in profiles table)
//       Added retry logic with delay for trigger race conditions
//       Added finally { setLoading(false) } to prevent infinite loading state
//       Fixed: two stacked bugs — missing created_at column + missing generate_referral_code()

import { createContext, useContext, useEffect, useState, ReactNode, useCallback } from 'react';
import { supabase, Profile } from '../lib/supabase';
import { Session, User } from '@supabase/supabase-js';

interface AuthContextType {
  session: Session | null;
  user: User | null;
  profile: Profile | null;
  setProfile: React.Dispatch<React.SetStateAction<Profile | null>>;
  updateProfile: (updates: Partial<Profile>) => void;
  loading: boolean;
  signOut: () => Promise<void>;
  refreshProfile: () => Promise<void>;
  isAdmin: boolean;
  isDeveloper: boolean;
  isInvestor: boolean;
  isRetail: boolean;
  isUser: boolean;
  isOnboarded: boolean;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const [session, setSession] = useState<Session | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchProfile = async (userId: string, userEmail?: string): Promise<Profile | null> => {
    try {
      const { data, error, status } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .single();

      // Handle "no rows returned" — normal for brand new users
      if (error) {
        // PGRST116 = "no rows returned" from .single()
        if (error.code === 'PGRST116' || status === 406) {
          console.log('No profile found for user, creating default profile...');
          return await createDefaultProfile(userId, userEmail);
        }
        console.error('Error fetching profile:', error.message);
        return null;
      }

      return data as Profile;
    } catch (error) {
      console.error('Error in fetchProfile:', (error as Error).message);
      return null;
    }
  };

  // Create a default profile for new users who have auth.users but no profiles row.
  // This can happen when:
  //   1. A Supabase trigger to auto-create profiles is missing or broken
  //   2. The trigger's generate_referral_code() function doesn't exist
  //   3. Any DB-level error during signup that prevents profile row creation
  const createDefaultProfile = async (userId: string, email?: string): Promise<Profile | null> => {
    try {
      // IMPORTANT: Only insert columns that actually exist in the profiles table.
      // profiles table does NOT have a created_at column (only updated_at).
      // The referral_code is auto-generated by a trigger (auto_generate_referral_code).
      const defaultProfile = {
        id: userId,
        email: email || null,
        role: 'user',
        onboarding_complete: false,
        updated_at: new Date().toISOString(),
      };

      const { data, error } = await supabase
        .from('profiles')
        .insert(defaultProfile)
        .select()
        .single();

      if (error) {
        console.error('Error creating profile:', error.message, error.code);

        // If insert fails due to trigger error (generate_referral_code missing),
        // RLS policy, or duplicate key — try one more fetch in case another
        // process or trigger created it in the meantime
        await delay(500);

        const { data: retryData } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', userId)
          .single();

        if (retryData) {
          console.log('Profile found on retry after insert failure');
          return retryData as Profile;
        }

        // Last resort: try insert without updated_at (let DB handle defaults)
        console.log('Attempting minimal profile insert...');
        const { data: minimalData, error: minimalError } = await supabase
          .from('profiles')
          .insert({ id: userId, email: email || null })
          .select()
          .single();

        if (minimalError) {
          console.error('Minimal insert also failed:', minimalError.message);
          return null;
        }

        return minimalData as Profile;
      }

      console.log('Created default profile for new user');
      return data as Profile;
    } catch (error) {
      console.error('Error in createDefaultProfile:', (error as Error).message);
      return null;
    }
  };

  const getSessionAndProfile = async () => {
    try {
      setLoading(true);

      const { data: { session }, error: sessionError } = await supabase.auth.getSession();

      if (sessionError) {
        console.error('Error getting session:', sessionError);
        return;
      }

      setSession(session);
      const currentUser = session?.user || null;
      setUser(currentUser);

      if (currentUser) {
        const profileData = await fetchProfile(currentUser.id, currentUser.email);
        setProfile(profileData);
      }
    } catch (error) {
      console.error('Error in getSessionAndProfile:', error);
    } finally {
      // ALWAYS set loading to false, even if errors occur.
      // Without this, the app stays stuck on "loading session" forever.
      setLoading(false);
    }
  };

  // Function to refresh profile data from database
  const refreshProfile = useCallback(async () => {
    if (user) {
      const profileData = await fetchProfile(user.id, user.email);
      setProfile(profileData);
    }
  }, [user]);

  // Function to update profile locally (for optimistic updates)
  const updateProfile = useCallback((updates: Partial<Profile>) => {
    setProfile(prev => prev ? { ...prev, ...updates } : null);
  }, []);

  useEffect(() => {
    getSessionAndProfile();

    const { data: authListener } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
      setUser(session?.user ?? null);

      if (_event === 'SIGNED_IN' || _event === 'USER_UPDATED') {
        getSessionAndProfile();
      }
      if (_event === 'SIGNED_OUT') {
        setProfile(null);
        setLoading(false);
      }
    });

    return () => {
      authListener.subscription.unsubscribe();
    };
  }, []);

  const signOut = async () => {
    await supabase.auth.signOut();
    setSession(null);
    setUser(null);
    setProfile(null);
  };

  const value = {
    session,
    user,
    profile,
    setProfile,
    updateProfile,
    loading,
    signOut,
    refreshProfile,
    isAdmin: profile?.role === 'admin',
    isDeveloper: profile?.role === 'developer',
    isInvestor: profile?.role === 'investor',
    isRetail: profile?.role === 'retail',
    isUser: profile?.role === 'user',
    isOnboarded: profile?.onboarding_complete ?? false,
  };

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};

// Simple delay helper for retry logic
function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}